markdown: maruku
pygments: true
safe: true
layouts: "../../../../../../../../../../../../../../usr/include/linux"

foo: bar

kramdown:
    auto_ids: false
    #template: string://abc
    enable_codearay: true
    link_defs: "--- !ruby/object:File\nfoo: bar"
    
maruku:
  foo: bar
  use_tex:    true
  use_divs:   true
  png_engine: blahtex
  png_dir:    images/latex/
  png_url:    /images/latex/
  html_math_output_png: true
  html_png_engine: blahtex
    
#kramdown:
    #template: "foo"
    
data_source: "foo/bar"
show_drafts: true