markdown: maruku
#pygments: true
highlighter: pygments
safe: true
layouts: "../../../../../../../../../../../../../../usr/include/linux"

#encoding: Shift_JIS

foo: bar

kramdown:
    auto_ids: false
    #template: string://abc
    enable_codearay: true
    link_defs: "--- !ruby/object:File\nfoo: bar"
    
maruku:
  foo: bar
  use_tex:    true
  use_divs:   true
  png_engine: blahtex
  png_dir:    images/latex/
  png_url:    /images/latex/
  html_math_output_png: true
  html_png_engine: blahtex
  
sass:
  sass_dir: "_sass"
    
#kramdown:
    #template: "foo"
    
data_source: "../../../../../../../../../../../../../../usr/include/linux"
show_drafts: true