markdown: kramdown
#pygments: true
highlighter: pygments
safe: true
jailed: false
foo24323: bar23483
keep_files: []
#layouts: "../../../../../../../../../../../../../../usr/include/linux"

#encoding: Shift_JIS

foo: bar

kramdown:
    :template: /etc/mime.types
    auto_ids: false
    #template: string://abc
    enable_codearay: true
    link_defs: |
        {
            "link1": ["link1url", {
                item1: !ruby/class "ClassBuilder"
                
            }]
        }
#     xlink_defs: |
#         --- !ruby/object:Celluloid::PoolManager
#             template:
#                 src: !binary |-
#                     cHV0cyAiaGVsbG8i"
maruku:
  foo: bar
  use_tex:    true
  use_divs:   true
  png_engine: blahtex
  png_dir:    images/latex/
  png_url:    /images/latex/
  html_math_output_png: true
  html_png_engine: blahtex
  
sass:
  sass_dir: "_sass"
    
#kramdown:
    #template: "foo"
    
data_source: "../../../../../../../../../../../../../../usr/include/linux"
show_drafts: true