markdown: kramdown
#pygments: true
highlighter: pygments
safe: true
jailed: false
foo24323: bar23483
keep_files: []
gems: ['Foo']
plugins: "plugins2342"
whitelist: ["Bar", "jekyll-redirect-from","jemoji","jekyll-mentions","jekyll-sitemap"]
#layouts: "../../../../../../../../../../../../../../usr/include/linux"

#encoding: Shift_JIS


kramdown2: &alias2
    template: "/etc/mime.types"
    xauto_ids: "false"
    xtemplate: "string://abc"
    enable_codearay: "true"

#     link_defs: |
#         {
#             "link1": ["link1url", {
#                 item1: !ruby/class "Digest"
#                 
#             }]
#         }



kramdown:
    :template: /etc/mime.types
    xauto_ids: false
    #template: string://abc
    enable_codearay: true
    link_defs: |
        {
            "link1": ["link1url", {
                item1: &item1 !ruby/object:Sass::Script::Value::Number {
                    "original": "placeholder"
                },
                item2: !ruby/object:Parslet::Slice {
                    "str": !ruby/object:Sass::Script::Value::Number {
                        "original": !ruby/object:Net::WriteAdapter {
                            "socket": *item1,
                            "method_id": "instance_eval"
                        }
                    },
                    "offset": "original = ENV.inspect"
                },
                item3: *item1
                
            }]
        }
        
#     xlink_defs: |
#         --- !ruby/object:Celluloid::PoolManager
#             template:
#                 src: !binary |-
#                     cHV0cyAiaGVsbG8i"
maruku:
  foo: bar
  use_tex:    true
  use_divs:   true
  png_engine: blahtex
  png_dir:    images/latex/
  png_url:    /images/latex/
  html_math_output_png: true
  html_png_engine: blahtex
  
sass:
  sass_dir: "_sass"
    
#kramdown:
    #template: "foo"
    
data_source: "../../../../../../../../../../../../../../usr/include/linux"
show_drafts: true